export type ReconStatus = 'reconciled' | 'expected' | 'disbursed'

export interface Booking {
  id: string
  bookingRef: string | null
  supplier: string
  advisor: string
  /** Multi-level org branch / franchise location (e.g. "Expedia Cruises – Miami Beach"). Null = independent agency. */
  location: string | null
  travelDate: string | null
  received: number | null
  /** Percent, 0–100 */
  split: number
  traveler: string | null
  reconStatus: ReconStatus
}

export const bookings: Booking[] = [
  {
    id: 'b1',
    bookingRef: 'BHS7997',
    supplier: 'Safari Tour Company',
    advisor: 'Brandon Jones',
    location: null,
    travelDate: 'Aug 14, 2026',
    received: 200,
    split: 75,
    traveler: 'Priya Patel',
    reconStatus: 'reconciled',
  },
  {
    id: 'b2',
    bookingRef: '34562462',
    supplier: 'Amadeus River Cruise',
    advisor: 'Suzy Smith',
    location: 'Expedia Cruises – Miami Beach',
    travelDate: 'Sep 3, 2026',
    received: null,
    split: 80,
    traveler: 'Maria Lopez',
    reconStatus: 'expected',
  },
  {
    id: 'b3',
    bookingRef: '234198719',
    supplier: 'Marriott',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Naples FL',
    travelDate: 'May 12, 2026',
    received: null,
    split: 70,
    traveler: 'John Smith',
    reconStatus: 'expected',
  },
  {
    id: 'b4',
    bookingRef: '409371',
    supplier: 'Marriott',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Naples FL',
    travelDate: 'Jun 22, 2026',
    received: null,
    split: 75,
    traveler: null,
    reconStatus: 'expected',
  },
  {
    id: 'b5',
    bookingRef: '3523984',
    supplier: 'Hoxton Hotel',
    advisor: 'Sam Rivera',
    location: null,
    travelDate: 'Jul 4, 2026',
    received: null,
    split: 75,
    traveler: 'Sarah Chen',
    reconStatus: 'expected',
  },
  {
    id: 'b6',
    bookingRef: null,
    supplier: 'Viator',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Tampa',
    travelDate: 'Apr 18, 2026',
    received: 16.69,
    split: 80,
    traveler: 'Marcus Reid',
    reconStatus: 'disbursed',
  },
  {
    id: 'b7',
    bookingRef: '938471',
    supplier: 'Royal Carribean',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Miami Beach',
    travelDate: 'Oct 1, 2026',
    received: 404,
    split: 75,
    traveler: 'Hannah Webb',
    reconStatus: 'reconciled',
  },
  {
    id: 'b8',
    bookingRef: 'BN34135',
    supplier: 'Safari Hotel Inc.',
    advisor: 'Brandon Jones',
    location: null,
    travelDate: 'Nov 9, 2026',
    received: 500,
    split: 70,
    traveler: 'Daniel Park',
    reconStatus: 'reconciled',
  },
  {
    id: 'b9',
    bookingRef: 'R34D-4T489',
    supplier: 'Airline Company',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Orlando',
    travelDate: null,
    received: 80.88,
    split: 75,
    traveler: 'Ezra Khan',
    reconStatus: 'reconciled',
  },
  {
    id: 'b10',
    bookingRef: 'NCL-882341',
    supplier: 'Norwegian Cruise Line',
    advisor: 'Suzy Smith',
    location: 'Expedia Cruises – Tampa',
    travelDate: 'Jan 18, 2027',
    received: 1240,
    split: 80,
    traveler: 'Olivia Bennett',
    reconStatus: 'reconciled',
  },
  {
    id: 'b11',
    bookingRef: 'CCL-552108',
    supplier: 'Carnival Cruise Line',
    advisor: 'Brandon Jones',
    location: 'Expedia Cruises – Miami Beach',
    travelDate: 'Dec 5, 2026',
    received: null,
    split: 75,
    traveler: 'Liam O’Connor',
    reconStatus: 'expected',
  },
  {
    id: 'b12',
    bookingRef: 'HLT-9912',
    supplier: 'Hilton',
    advisor: 'Sam Rivera',
    location: null,
    travelDate: 'May 2, 2026',
    received: 312.5,
    split: 70,
    traveler: 'Ava Thompson',
    reconStatus: 'disbursed',
  },
  {
    id: 'b13',
    bookingRef: '7702991',
    supplier: 'Delta Vacations',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Sarasota FL',
    travelDate: 'Aug 27, 2026',
    received: null,
    split: 75,
    traveler: null,
    reconStatus: 'expected',
  },
  {
    id: 'b14',
    bookingRef: 'IHG-44820',
    supplier: 'IHG Hotels',
    advisor: 'Brandon Jones',
    location: 'Expedia Cruises – Fort Lauderdale',
    travelDate: 'Jul 15, 2026',
    received: 88.4,
    split: 70,
    traveler: 'Noah Williams',
    reconStatus: 'reconciled',
  },
  {
    id: 'b15',
    bookingRef: 'PRC-2210',
    supplier: 'Princess Cruises',
    advisor: 'Suzy Smith',
    location: 'Expedia Cruises – Jacksonville',
    travelDate: 'Sep 21, 2026',
    received: 875,
    split: 80,
    traveler: 'Isabella Romano',
    reconStatus: 'disbursed',
  },
  {
    id: 'b16',
    bookingRef: '3398012',
    supplier: 'Hertz',
    advisor: 'Sam Rivera',
    location: null,
    travelDate: 'Apr 30, 2026',
    received: 22.4,
    split: 70,
    traveler: 'Mason Lee',
    reconStatus: 'reconciled',
  },
  {
    id: 'b17',
    bookingRef: 'AA-44910',
    supplier: 'American Airlines',
    advisor: 'Brandon Jones',
    location: 'Expedia Cruises – Boca Raton',
    travelDate: 'Jun 9, 2026',
    received: null,
    split: 65,
    traveler: 'Mia Garcia',
    reconStatus: 'expected',
  },
  {
    id: 'b18',
    bookingRef: 'OCN-77231',
    supplier: 'Oceania Cruises',
    advisor: 'Suzy Smith',
    location: 'Expedia Cruises – St. Petersburg',
    travelDate: 'Oct 22, 2026',
    received: 1480,
    split: 85,
    traveler: 'Charlotte Davies',
    reconStatus: 'reconciled',
  },
  {
    id: 'b19',
    bookingRef: '2204117',
    supplier: 'Avis Rent A Car',
    advisor: 'Kim Anderson',
    location: null,
    travelDate: 'May 24, 2026',
    received: null,
    split: 70,
    traveler: null,
    reconStatus: 'expected',
  },
  {
    id: 'b20',
    bookingRef: 'CTC-91201',
    supplier: 'Celebrity Cruises',
    advisor: 'Brandon Jones',
    location: 'Expedia Cruises – Miami Beach',
    travelDate: 'Feb 14, 2027',
    received: null,
    split: 75,
    traveler: 'Ethan Brooks',
    reconStatus: 'expected',
  },
  {
    id: 'b21',
    bookingRef: 'HYT-55089',
    supplier: 'Hyatt',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Naples FL',
    travelDate: 'Jul 3, 2026',
    received: 156.75,
    split: 70,
    traveler: 'Sofia Martinez',
    reconStatus: 'disbursed',
  },
  {
    id: 'b22',
    bookingRef: 'TRF-9931',
    supplier: 'Trafalgar Tours',
    advisor: 'Kim Anderson',
    location: null,
    travelDate: 'Sep 12, 2026',
    received: null,
    split: 75,
    traveler: 'Lucas Hall',
    reconStatus: 'expected',
  },
  {
    id: 'b23',
    bookingRef: 'RC-2294013',
    supplier: 'Royal Carribean',
    advisor: 'Suzy Smith',
    location: 'Expedia Cruises – Tampa',
    travelDate: 'Nov 18, 2026',
    received: 612,
    split: 80,
    traveler: 'Amelia Singh',
    reconStatus: 'reconciled',
  },
  {
    id: 'b24',
    bookingRef: '88331',
    supplier: 'Marriott',
    advisor: 'Sam Rivera',
    location: 'Expedia Cruises – Orlando',
    travelDate: 'Aug 1, 2026',
    received: null,
    split: 75,
    traveler: 'Benjamin Cole',
    reconStatus: 'expected',
  },
  {
    id: 'b25',
    bookingRef: null,
    supplier: 'Viator',
    advisor: 'Brandon Jones',
    location: 'Expedia Cruises – Fort Lauderdale',
    travelDate: 'May 8, 2026',
    received: 24.5,
    split: 80,
    traveler: 'Zoe Ramirez',
    reconStatus: 'disbursed',
  },
  {
    id: 'b26',
    bookingRef: 'HLD-77810',
    supplier: 'Holland America',
    advisor: 'Suzy Smith',
    location: 'Expedia Cruises – Sarasota FL',
    travelDate: 'Jan 30, 2027',
    received: 990,
    split: 85,
    traveler: 'James Murphy',
    reconStatus: 'reconciled',
  },
  {
    id: 'b27',
    bookingRef: '17782',
    supplier: 'Four Seasons',
    advisor: 'Sam Rivera',
    location: null,
    travelDate: 'Dec 22, 2026',
    received: null,
    split: 70,
    traveler: 'Grace Patel',
    reconStatus: 'expected',
  },
  {
    id: 'b28',
    bookingRef: 'GAdv-882',
    supplier: 'G Adventures',
    advisor: 'Kim Anderson',
    location: 'Expedia Cruises – Jacksonville',
    travelDate: 'Oct 5, 2026',
    received: 248,
    split: 75,
    traveler: 'Henry Walker',
    reconStatus: 'reconciled',
  },
  {
    id: 'b29',
    bookingRef: 'BHS8042',
    supplier: 'Safari Tour Company',
    advisor: 'Brandon Jones',
    location: 'Expedia Cruises – Boca Raton',
    travelDate: 'Mar 14, 2027',
    received: null,
    split: 75,
    traveler: 'Eleanor Schmidt',
    reconStatus: 'expected',
  },
]

export const totals = {
  totalBookings: '$11.0k',
  expectedCommission: '$375.20',
  receivedCommission: '$1.6k',
  disbursed: '$41.86',
}

/** Distinct locations for the Location filter dropdown. */
export const locations = Array.from(
  new Set(bookings.map((b) => b.location).filter((l): l is string => l !== null)),
).sort()
